# Generated by Django 4.1.7 on 2023-03-29 17:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('School_sys', '0004_teachers_father_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('CLass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School_sys.s_clas')),
                ('Teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School_sys.teachers')),
            ],
        ),
    ]
