# Generated by Django 4.1.7 on 2023-03-31 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('School_sys', '0006_alter_session_year_session_start_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session_year',
            old_name='session_end',
            new_name='Session_end',
        ),
    ]
