# Generated by Django 4.1.7 on 2023-03-31 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('School_sys', '0008_alter_session_year_session_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='S_Class_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='School_sys.s_clas'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Session_year_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='School_sys.session_year'),
        ),
    ]
