# Generated by Django 4.1.7 on 2023-04-08 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('School_sys', '0012_alter_teachers_notification_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers_notification',
            name='status',
        ),
    ]
