# Generated by Django 4.1.7 on 2023-04-08 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School_sys', '0013_remove_teachers_notification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers_notification',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
