# Generated by Django 4.1.7 on 2023-04-10 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School_sys', '0015_teachers_leave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers_leave',
            name='subject',
        ),
        migrations.AddField(
            model_name='teachers_leave',
            name='date_from',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teachers_leave',
            name='date_to',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
