# Generated by Django 4.1.7 on 2023-04-11 01:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('School_sys', '0016_remove_teachers_leave_subject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.IntegerField(default=0, null=True)),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School_sys.s_clas')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School_sys.session_year')),
            ],
        ),
    ]
