# Generated by Django 4.1.7 on 2023-04-11 12:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('School_sys', '0018_alter_teachers_father_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students_Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.CharField(max_length=100, null=True)),
                ('date_to', models.CharField(max_length=100, null=True)),
                ('message', models.TextField()),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('Student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School_sys.student')),
            ],
        ),
    ]
