# Generated by Django 4.1.7 on 2023-04-12 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('School_sys', '0019_students_leave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='Teacher',
        ),
        migrations.AddField(
            model_name='subject',
            name='session',
            field=models.ForeignKey(default=16, on_delete=django.db.models.deletion.CASCADE, to='School_sys.session_year'),
        ),
    ]
