# Generated by Django 4.1.7 on 2023-04-12 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('School_sys', '0021_time_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='CLass',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='session',
        ),
    ]
