# Generated by Django 4.2 on 2023-04-15 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('School_sys', '0022_remove_subject_class_remove_subject_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('exam_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School_sys.session_year')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School_sys.s_clas')),
            ],
            options={
                'unique_together': {('session', 'student_class')},
            },
        ),
    ]
