# Generated by Django 4.2 on 2023-04-15 05:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('School_sys', '0023_setfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='setfee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setfee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
