# Generated by Django 4.2 on 2023-04-15 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('School_sys', '0024_setfee_created_at_setfee_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('set_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School_sys.setfee')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School_sys.student')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
