# Generated by Django 4.2 on 2023-04-15 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School_sys', '0025_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fee_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
