# Generated by Django 4.2 on 2023-04-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School_sys', '0026_student_fee_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setfee',
            name='exam_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='setfee',
            name='other_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
