# Generated by Django 4.2 on 2023-04-17 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School_sys', '0028_alter_setfee_monthly_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='setfee',
            name='end_month',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='setfee',
            name='start_month',
            field=models.CharField(default='N/A', max_length=20),
        ),
    ]
