# Generated by Django 4.2 on 2023-06-06 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('School_sys', '0029_setfee_end_month_setfee_start_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Attendence_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('S_class', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='School_sys.s_clas')),
                ('session_year', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='School_sys.session_year')),
            ],
        ),
        migrations.CreateModel(
            name='Attendence_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Attedence_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School_sys.attendence')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='School_sys.student')),
            ],
        ),
    ]
